<?xml version="1.0" encoding="utf-8"?><Database Name="Db_guia_5" Class="Data_Db_guia_5DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HORWELL-LENOVO-;Initial Catalog=Db_guia_5;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Db_guia_5ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Nombres" Member="Nombres">
    <Type Name="Nombre">
      <Column Name="Id_nombre" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Member="Nombre1" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>